# Generated by Django 5.1.14 on 2025-12-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0037_delete_externalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transient',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
